/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ViewAllRecord extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllRecord
     */
    DefaultTableModel Model;//this model will set values in the table>>>>>>

    public ViewAllRecord() {
        initComponents();
        setIssueBookDetailstoTable();
    }

    public void setIssueBookDetailstoTable() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "43593");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from issue_book_details");
            while (rs.next()) {
                String Id = rs.getString("id");
                String bookName = rs.getString("book_name");
                String student_name = rs.getString("student_name");
                String Issue_Date = rs.getString("issue_date");
                String Due_Date = rs.getString("due_date");
                String Status = rs.getString("status");

                Object[] obj = {Id, bookName, student_name, Issue_Date, Due_Date, Status};
                Model = (DefaultTableModel) tbl_IssueBookDetail.getModel();
                Model.addRow(obj);//this model will represent the table and it will take object..... so that is why we created object
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clearTable() {

        DefaultTableModel Model = (DefaultTableModel) tbl_IssueBookDetail.getModel(); ///we type casted the table model because the error 
//said we can not use tablemodel with default table model
        Model.setRowCount(0);//it will clear the table so that only data added will be dispalyed, remove all rows
    }
//fetch recorddd frommm databaseeee

    public void search() {
        Date ufromdate = from_date.getDatoFecha();
        Date utodate = to_date.getDatoFecha();//this date is an alag package and database uses sql date so we'll convert this date to use in that 

        Long l1 = ufromdate.getTime();
        long l2 = utodate.getTime();

        java.sql.Date sfromDate = new java.sql.Date(l1);/*in here in () weneed to provide 'long' value so we are getting it*/
        java.sql.Date stoDate = new java.sql.Date(l2);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root", "43593");
            String sql = "Select * from issue_book_details where issue_date Between ? and ?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setDate(1, sfromDate);
            pst.setDate(2, sfromDate);

            ResultSet rs = pst.executeQuery();
            if (rs.next() == true) {
                while (rs.next()) {
                    String Id = rs.getString("id");
                    String bookName = rs.getString("book_name");
                    String student_name = rs.getString("student_name");
                    String Issue_Date = rs.getString("issue_date");
                    String Due_Date = rs.getString("due_date");
                    String Status = rs.getString("status");

                    Object[] obj = {Id, bookName, student_name, Issue_Date, Due_Date, Status};
                    Model = (DefaultTableModel) tbl_IssueBookDetail.getModel();
                    Model.addRow(obj);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No Data Found");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        from_date = new rojeru_san.componentes.RSDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        to_date = new rojeru_san.componentes.RSDateChooser();
        Panel_Table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_IssueBookDetail = new rojerusan.RSTableMetro();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel12.setText("  View All Record");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 310, 110));

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 310, 5));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("x");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, -1, -1));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel11.setText("Back");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        from_date.setColorBackground(new java.awt.Color(102, 102, 102));
        from_date.setColorButtonHover(new java.awt.Color(204, 204, 204));
        from_date.setColorDiaActual(new java.awt.Color(102, 102, 102));
        from_date.setColorForeground(new java.awt.Color(0, 0, 0));
        from_date.setPlaceholder("Choose Date..");
        jPanel1.add(from_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 260, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText(" Issue Date :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 150, 40));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText(" Return Date :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, 40));

        to_date.setColorBackground(new java.awt.Color(102, 102, 102));
        to_date.setColorButtonHover(new java.awt.Color(204, 204, 204));
        to_date.setColorDiaActual(new java.awt.Color(102, 102, 102));
        to_date.setColorForeground(new java.awt.Color(0, 0, 0));
        to_date.setPlaceholder("Choose Date..");
        jPanel1.add(to_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 260, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 260));

        Panel_Table.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_IssueBookDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Name", "Student Id", "Issue Date", "Due Date", "Status"
            }
        ));
        tbl_IssueBookDetail.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        tbl_IssueBookDetail.setColorBordeFilas(new java.awt.Color(0, 153, 153));
        tbl_IssueBookDetail.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_IssueBookDetail.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_IssueBookDetail.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_IssueBookDetail.setColorSelBackgound(new java.awt.Color(153, 153, 153));
        tbl_IssueBookDetail.setFuenteFilas(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        tbl_IssueBookDetail.setFuenteFilasSelect(new java.awt.Font("Yu Gothic Light", 1, 20)); // NOI18N
        tbl_IssueBookDetail.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_IssueBookDetail.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_IssueBookDetail.setRowHeight(30);
        tbl_IssueBookDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_IssueBookDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_IssueBookDetail);

        Panel_Table.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 970, 220));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonCircle1.setText("Find");
        rSMaterialButtonCircle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle1MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle1ActionPerformed(evt);
            }
        });
        Panel_Table.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 140, 60));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonCircle2.setText("All Record");
        rSMaterialButtonCircle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle2MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        Panel_Table.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 120, 60));

        getContentPane().add(Panel_Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1460, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonCircle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1MouseClicked


    }//GEN-LAST:event_rSMaterialButtonCircle1MouseClicked

    private void rSMaterialButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1ActionPerformed
if(from_date.getDatoFecha() != null && to_date.getDatoFecha() != null){
    
        clearTable();
        search();
}else{
    JOptionPane.showMessageDialog(this, "Plz search a date .");
}
    }//GEN-LAST:event_rSMaterialButtonCircle1ActionPerformed

    private void tbl_IssueBookDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_IssueBookDetailMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_IssueBookDetailMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        homePage home = new homePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void rSMaterialButtonCircle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle2MouseClicked

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
        clearTable();
        setIssueBookDetailstoTable();
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Table;
    private rojeru_san.componentes.RSDateChooser from_date;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private rojerusan.RSTableMetro tbl_IssueBookDetail;
    private rojeru_san.componentes.RSDateChooser to_date;
    // End of variables declaration//GEN-END:variables
}
